### ISSUE TITLE
Add Journal by whodunnit

### ISSUE THREAD

**Issue by tjchambers** [tjchambers/paper_trail_scrapbook#14]
Would like to be able to get output in LifeHistory style human readable form of the details filtered by whodunnit over a time range. This would have to add the item being altered to the LifeHistory style output since the context would be a whodunnit individual.

**Comment by dinjas** [comment]
Maybe called by something like `PaperTrail::Scrapbook::UserStory.new(user, start_time, end_time).story`?

**Comment by tjchambers** [comment]
yes - would be also nice perhaps to be able to filter on item class.

**Comment by tjchambers** [comment]
probably would prefer UserJournal as a name to distance it from being a simple story
